$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - node_modules
enabledLanguageIds:
  - "*"
words:
  - ador
  - ainai
  - amatar
  - arrayfy
  - astro
  - astrojs
  - certbot
  - composables
  - csso
  - dhparams
  - Diffie
  - distroless
  - dpage
  - ENVSUBST
  - fontsource
  - fullchain
  - furuyama
  - gaku
  - genki
  - GIGA
  - gohho
  - gura
  - hinode
  - itnav
  - jonasal
  - keyframes
  - keyscan
  - kubo
  - Laravel
  - letsencrypt
  - lockb
  - matoi
  - MICROCMS
  - minmax
  - multipass
  - nabukatu
  - nanoquery
  - nanostore
  - nanostores
  - noopener
  - noreferrer
  - noto
  - nowrap
  - nuxt
  - onwarn
  - ozaki
  - PGADMIN
  - PGWEB
  - playform
  - prerender
  - privkey
  - proto
  - prototools
  - purgecss
  - renren
  - reuseport
  - rgba
  - roboto
  - rohan
  - sansan
  - shigure
  - sitemapindex
  - sosedoff
  - stylelint
  - swiper
  - takana
  - takayuki
  - tama
  - tbody
  - tsconfigs
  - tsdoc
  - typeof
  - urlset
  - yottu
  - yume
  - yuza
  - zack
